# Generated by Django 3.0.2 on 2020-02-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(null=True)),
                ('unit_of_measure', models.CharField(choices=[('L', 'Liter'), ('G', 'Gallon')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_model', models.TextField()),
                ('meter_vendor', models.TextField()),
            ],
            options={
                'unique_together': {('meter_model', 'meter_vendor')},
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_serial', models.TextField(unique=True)),
                ('install_date', models.DateTimeField(auto_now=True)),
                ('retire_date', models.DateTimeField(null=True)),
                ('meter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MeterType')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField()),
                ('reading', models.BigIntegerField()),
                ('unit_of_measure', models.CharField(choices=[('L', 'Liter'), ('G', 'Gallon')], max_length=1)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Asset_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meter')),
            ],
        ),
    ]
